micronaut:
  application:
    name: microcrud
datasources:
  default:
    url: jdbc:h2:mem:spaceship;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE
    username: sa
    password: ''
    driver-class-name: org.h2.Driver
    schema-generate: CREATE_DROP
    dialect: H2
jpa.default.properties.hibernate.hbm2ddl.auto: update
jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
